// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/auctionsystem.proto

package auctionsystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_ONGOING State = 0
	State_LOST    State = 1
	State_WON     State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "ONGOING",
		1: "LOST",
		2: "WON",
	}
	State_value = map[string]int32{
		"ONGOING": 0,
		"LOST":    1,
		"WON":     2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auctionsystem_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_grpc_auctionsystem_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{0}
}

type Ack int32

const (
	Ack_FAIL      Ack = 0
	Ack_SUCCESS   Ack = 1
	Ack_EXCEPTION Ack = 2
)

// Enum value maps for Ack.
var (
	Ack_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
	}
	Ack_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
	}
)

func (x Ack) Enum() *Ack {
	p := new(Ack)
	*p = x
	return p
}

func (x Ack) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ack) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auctionsystem_proto_enumTypes[1].Descriptor()
}

func (Ack) Type() protoreflect.EnumType {
	return &file_grpc_auctionsystem_proto_enumTypes[1]
}

func (x Ack) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ack.Descriptor instead.
func (Ack) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{1}
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Id            *UUID                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Amount) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{1}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Resultmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Highestbidder *UUID                  `protobuf:"bytes,1,opt,name=highestbidder,proto3,oneof" json:"highestbidder,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=auctionsystem.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resultmsg) Reset() {
	*x = Resultmsg{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resultmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resultmsg) ProtoMessage() {}

func (x *Resultmsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resultmsg.ProtoReflect.Descriptor instead.
func (*Resultmsg) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{2}
}

func (x *Resultmsg) GetHighestbidder() *UUID {
	if x != nil {
		return x.Highestbidder
	}
	return nil
}

func (x *Resultmsg) GetState() State {
	if x != nil {
		return x.State
	}
	return State_ONGOING
}

type Ackmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           Ack                    `protobuf:"varint,1,opt,name=ack,proto3,enum=auctionsystem.Ack" json:"ack,omitempty"`
	Exception     *string                `protobuf:"bytes,2,opt,name=exception,proto3,oneof" json:"exception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ackmsg) Reset() {
	*x = Ackmsg{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ackmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ackmsg) ProtoMessage() {}

func (x *Ackmsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ackmsg.ProtoReflect.Descriptor instead.
func (*Ackmsg) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{3}
}

func (x *Ackmsg) GetAck() Ack {
	if x != nil {
		return x.Ack
	}
	return Ack_FAIL
}

func (x *Ackmsg) GetException() string {
	if x != nil && x.Exception != nil {
		return *x.Exception
	}
	return ""
}

var File_grpc_auctionsystem_proto protoreflect.FileDescriptor

const file_grpc_auctionsystem_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/auctionsystem.proto\x12\rauctionsystem\"E\n" +
	"\x06amount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12#\n" +
	"\x02id\x18\x02 \x01(\v2\x13.auctionsystem.UUIDR\x02id\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x89\x01\n" +
	"\tresultmsg\x12>\n" +
	"\rhighestbidder\x18\x01 \x01(\v2\x13.auctionsystem.UUIDH\x00R\rhighestbidder\x88\x01\x01\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.auctionsystem.stateR\x05stateB\x10\n" +
	"\x0e_highestbidder\"_\n" +
	"\x06ackmsg\x12$\n" +
	"\x03ack\x18\x01 \x01(\x0e2\x12.auctionsystem.ackR\x03ack\x12!\n" +
	"\texception\x18\x02 \x01(\tH\x00R\texception\x88\x01\x01B\f\n" +
	"\n" +
	"_exception*'\n" +
	"\x05state\x12\v\n" +
	"\aONGOING\x10\x00\x12\b\n" +
	"\x04LOST\x10\x01\x12\a\n" +
	"\x03WON\x10\x02*+\n" +
	"\x03ack\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x022{\n" +
	"\aAuction\x125\n" +
	"\x03Bid\x12\x15.auctionsystem.amount\x1a\x15.auctionsystem.ackmsg\"\x00\x129\n" +
	"\x06Result\x12\x13.auctionsystem.UUID\x1a\x18.auctionsystem.resultmsg\"\x00B:Z8github.com/Mojjedrengen/AuctionSystem/grpc/auctionsystemb\x06proto3"

var (
	file_grpc_auctionsystem_proto_rawDescOnce sync.Once
	file_grpc_auctionsystem_proto_rawDescData []byte
)

func file_grpc_auctionsystem_proto_rawDescGZIP() []byte {
	file_grpc_auctionsystem_proto_rawDescOnce.Do(func() {
		file_grpc_auctionsystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auctionsystem_proto_rawDesc), len(file_grpc_auctionsystem_proto_rawDesc)))
	})
	return file_grpc_auctionsystem_proto_rawDescData
}

var file_grpc_auctionsystem_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_auctionsystem_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_auctionsystem_proto_goTypes = []any{
	(State)(0),        // 0: auctionsystem.state
	(Ack)(0),          // 1: auctionsystem.ack
	(*Amount)(nil),    // 2: auctionsystem.amount
	(*UUID)(nil),      // 3: auctionsystem.UUID
	(*Resultmsg)(nil), // 4: auctionsystem.resultmsg
	(*Ackmsg)(nil),    // 5: auctionsystem.ackmsg
}
var file_grpc_auctionsystem_proto_depIdxs = []int32{
	3, // 0: auctionsystem.amount.id:type_name -> auctionsystem.UUID
	3, // 1: auctionsystem.resultmsg.highestbidder:type_name -> auctionsystem.UUID
	0, // 2: auctionsystem.resultmsg.state:type_name -> auctionsystem.state
	1, // 3: auctionsystem.ackmsg.ack:type_name -> auctionsystem.ack
	2, // 4: auctionsystem.Auction.Bid:input_type -> auctionsystem.amount
	3, // 5: auctionsystem.Auction.Result:input_type -> auctionsystem.UUID
	5, // 6: auctionsystem.Auction.Bid:output_type -> auctionsystem.ackmsg
	4, // 7: auctionsystem.Auction.Result:output_type -> auctionsystem.resultmsg
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_auctionsystem_proto_init() }
func file_grpc_auctionsystem_proto_init() {
	if File_grpc_auctionsystem_proto != nil {
		return
	}
	file_grpc_auctionsystem_proto_msgTypes[2].OneofWrappers = []any{}
	file_grpc_auctionsystem_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auctionsystem_proto_rawDesc), len(file_grpc_auctionsystem_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auctionsystem_proto_goTypes,
		DependencyIndexes: file_grpc_auctionsystem_proto_depIdxs,
		EnumInfos:         file_grpc_auctionsystem_proto_enumTypes,
		MessageInfos:      file_grpc_auctionsystem_proto_msgTypes,
	}.Build()
	File_grpc_auctionsystem_proto = out.File
	file_grpc_auctionsystem_proto_goTypes = nil
	file_grpc_auctionsystem_proto_depIdxs = nil
}
