// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: grpc/auctionsystem.proto

package auctionsystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_ONGOING State = 0
	State_DONE    State = 1
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "ONGOING",
		1: "DONE",
	}
	State_value = map[string]int32{
		"ONGOING": 0,
		"DONE":    1,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auctionsystem_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_grpc_auctionsystem_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{0}
}

type Ack int32

const (
	Ack_FAIL      Ack = 0
	Ack_SUCCESS   Ack = 1
	Ack_EXCEPTION Ack = 2
)

// Enum value maps for Ack.
var (
	Ack_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
	}
	Ack_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
	}
)

func (x Ack) Enum() *Ack {
	p := new(Ack)
	*p = x
	return p
}

func (x Ack) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ack) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auctionsystem_proto_enumTypes[1].Descriptor()
}

func (Ack) Type() protoreflect.EnumType {
	return &file_grpc_auctionsystem_proto_enumTypes[1]
}

func (x Ack) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ack.Descriptor instead.
func (Ack) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{1}
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Id            *UUID                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Amount) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{1}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Resultmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Highestbidder *UUID                  `protobuf:"bytes,1,opt,name=highestbidder,proto3" json:"highestbidder,omitempty"`
	State         State                  `protobuf:"varint,2,opt,name=state,proto3,enum=auctionsystem.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resultmsg) Reset() {
	*x = Resultmsg{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resultmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resultmsg) ProtoMessage() {}

func (x *Resultmsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resultmsg.ProtoReflect.Descriptor instead.
func (*Resultmsg) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{2}
}

func (x *Resultmsg) GetHighestbidder() *UUID {
	if x != nil {
		return x.Highestbidder
	}
	return nil
}

func (x *Resultmsg) GetState() State {
	if x != nil {
		return x.State
	}
	return State_ONGOING
}

type ClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       map[uint64]string      `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterInfo) GetMembers() map[uint64]string {
	if x != nil {
		return x.Members
	}
	return nil
}

type Ackmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           Ack                    `protobuf:"varint,1,opt,name=ack,proto3,enum=auctionsystem.Ack" json:"ack,omitempty"`
	Exception     *string                `protobuf:"bytes,2,opt,name=exception,proto3,oneof" json:"exception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ackmsg) Reset() {
	*x = Ackmsg{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ackmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ackmsg) ProtoMessage() {}

func (x *Ackmsg) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ackmsg.ProtoReflect.Descriptor instead.
func (*Ackmsg) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{4}
}

func (x *Ackmsg) GetAck() Ack {
	if x != nil {
		return x.Ack
	}
	return Ack_FAIL
}

func (x *Ackmsg) GetException() string {
	if x != nil && x.Exception != nil {
		return *x.Exception
	}
	return ""
}

type Self struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Self) Reset() {
	*x = Self{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Self) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Self) ProtoMessage() {}

func (x *Self) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Self.ProtoReflect.Descriptor instead.
func (*Self) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{5}
}

func (x *Self) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Self) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuctionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Highestbidder *UUID                  `protobuf:"bytes,1,opt,name=highestbidder,proto3" json:"highestbidder,omitempty"`
	HighestBid    uint64                 `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	KnownBidders  []*UUID                `protobuf:"bytes,3,rep,name=knownBidders,proto3" json:"knownBidders,omitempty"`
	BidTimeFrame  uint32                 `protobuf:"varint,4,opt,name=bidTimeFrame,proto3" json:"bidTimeFrame,omitempty"`
	BidStartTime  uint64                 `protobuf:"varint,5,opt,name=bidStartTime,proto3" json:"bidStartTime,omitempty"`
	LastWonBidder *UUID                  `protobuf:"bytes,6,opt,name=lastWonBidder,proto3" json:"lastWonBidder,omitempty"`
	IsBitOngoin   bool                   `protobuf:"varint,7,opt,name=isBitOngoin,proto3" json:"isBitOngoin,omitempty"`
	State         State                  `protobuf:"varint,8,opt,name=state,proto3,enum=auctionsystem.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionData) Reset() {
	*x = AuctionData{}
	mi := &file_grpc_auctionsystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionData) ProtoMessage() {}

func (x *AuctionData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auctionsystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionData.ProtoReflect.Descriptor instead.
func (*AuctionData) Descriptor() ([]byte, []int) {
	return file_grpc_auctionsystem_proto_rawDescGZIP(), []int{6}
}

func (x *AuctionData) GetHighestbidder() *UUID {
	if x != nil {
		return x.Highestbidder
	}
	return nil
}

func (x *AuctionData) GetHighestBid() uint64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *AuctionData) GetKnownBidders() []*UUID {
	if x != nil {
		return x.KnownBidders
	}
	return nil
}

func (x *AuctionData) GetBidTimeFrame() uint32 {
	if x != nil {
		return x.BidTimeFrame
	}
	return 0
}

func (x *AuctionData) GetBidStartTime() uint64 {
	if x != nil {
		return x.BidStartTime
	}
	return 0
}

func (x *AuctionData) GetLastWonBidder() *UUID {
	if x != nil {
		return x.LastWonBidder
	}
	return nil
}

func (x *AuctionData) GetIsBitOngoin() bool {
	if x != nil {
		return x.IsBitOngoin
	}
	return false
}

func (x *AuctionData) GetState() State {
	if x != nil {
		return x.State
	}
	return State_ONGOING
}

var File_grpc_auctionsystem_proto protoreflect.FileDescriptor

const file_grpc_auctionsystem_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/auctionsystem.proto\x12\rauctionsystem\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x06amount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12#\n" +
	"\x02id\x18\x02 \x01(\v2\x13.auctionsystem.UUIDR\x02id\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"r\n" +
	"\tresultmsg\x129\n" +
	"\rhighestbidder\x18\x01 \x01(\v2\x13.auctionsystem.UUIDR\rhighestbidder\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.auctionsystem.stateR\x05state\"\x8c\x01\n" +
	"\vClusterInfo\x12A\n" +
	"\amembers\x18\x01 \x03(\v2'.auctionsystem.ClusterInfo.MembersEntryR\amembers\x1a:\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x06ackmsg\x12$\n" +
	"\x03ack\x18\x01 \x01(\x0e2\x12.auctionsystem.ackR\x03ack\x12!\n" +
	"\texception\x18\x02 \x01(\tH\x00R\texception\x88\x01\x01B\f\n" +
	"\n" +
	"_exception\"0\n" +
	"\x04self\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"\xf2\x02\n" +
	"\vAuctionData\x129\n" +
	"\rhighestbidder\x18\x01 \x01(\v2\x13.auctionsystem.UUIDR\rhighestbidder\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x02 \x01(\x04R\n" +
	"highestBid\x127\n" +
	"\fknownBidders\x18\x03 \x03(\v2\x13.auctionsystem.UUIDR\fknownBidders\x12\"\n" +
	"\fbidTimeFrame\x18\x04 \x01(\rR\fbidTimeFrame\x12\"\n" +
	"\fbidStartTime\x18\x05 \x01(\x04R\fbidStartTime\x129\n" +
	"\rlastWonBidder\x18\x06 \x01(\v2\x13.auctionsystem.UUIDR\rlastWonBidder\x12 \n" +
	"\visBitOngoin\x18\a \x01(\bR\visBitOngoin\x12*\n" +
	"\x05state\x18\b \x01(\x0e2\x14.auctionsystem.stateR\x05state*\x1e\n" +
	"\x05state\x12\v\n" +
	"\aONGOING\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01*+\n" +
	"\x03ack\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x022~\n" +
	"\aAuction\x125\n" +
	"\x03Bid\x12\x15.auctionsystem.amount\x1a\x15.auctionsystem.ackmsg\"\x00\x12<\n" +
	"\x06Result\x12\x16.google.protobuf.Empty\x1a\x18.auctionsystem.resultmsg\"\x002\x87\x02\n" +
	"\x0fReplicationSync\x12:\n" +
	"\x05Fetch\x12\x13.auctionsystem.self\x1a\x1a.auctionsystem.AuctionData\"\x00\x12:\n" +
	"\tHeartbeat\x12\x13.auctionsystem.self\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\fRegisterNode\x12\x13.auctionsystem.self\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\n" +
	"GetCluster\x12\x13.auctionsystem.self\x1a\x1a.auctionsystem.ClusterInfoB:Z8github.com/Mojjedrengen/AuctionSystem/grpc/auctionsystemb\x06proto3"

var (
	file_grpc_auctionsystem_proto_rawDescOnce sync.Once
	file_grpc_auctionsystem_proto_rawDescData []byte
)

func file_grpc_auctionsystem_proto_rawDescGZIP() []byte {
	file_grpc_auctionsystem_proto_rawDescOnce.Do(func() {
		file_grpc_auctionsystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auctionsystem_proto_rawDesc), len(file_grpc_auctionsystem_proto_rawDesc)))
	})
	return file_grpc_auctionsystem_proto_rawDescData
}

var file_grpc_auctionsystem_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_auctionsystem_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_auctionsystem_proto_goTypes = []any{
	(State)(0),            // 0: auctionsystem.state
	(Ack)(0),              // 1: auctionsystem.ack
	(*Amount)(nil),        // 2: auctionsystem.amount
	(*UUID)(nil),          // 3: auctionsystem.UUID
	(*Resultmsg)(nil),     // 4: auctionsystem.resultmsg
	(*ClusterInfo)(nil),   // 5: auctionsystem.ClusterInfo
	(*Ackmsg)(nil),        // 6: auctionsystem.ackmsg
	(*Self)(nil),          // 7: auctionsystem.self
	(*AuctionData)(nil),   // 8: auctionsystem.AuctionData
	nil,                   // 9: auctionsystem.ClusterInfo.MembersEntry
	(*emptypb.Empty)(nil), // 10: google.protobuf.Empty
}
var file_grpc_auctionsystem_proto_depIdxs = []int32{
	3,  // 0: auctionsystem.amount.id:type_name -> auctionsystem.UUID
	3,  // 1: auctionsystem.resultmsg.highestbidder:type_name -> auctionsystem.UUID
	0,  // 2: auctionsystem.resultmsg.state:type_name -> auctionsystem.state
	9,  // 3: auctionsystem.ClusterInfo.members:type_name -> auctionsystem.ClusterInfo.MembersEntry
	1,  // 4: auctionsystem.ackmsg.ack:type_name -> auctionsystem.ack
	3,  // 5: auctionsystem.AuctionData.highestbidder:type_name -> auctionsystem.UUID
	3,  // 6: auctionsystem.AuctionData.knownBidders:type_name -> auctionsystem.UUID
	3,  // 7: auctionsystem.AuctionData.lastWonBidder:type_name -> auctionsystem.UUID
	0,  // 8: auctionsystem.AuctionData.state:type_name -> auctionsystem.state
	2,  // 9: auctionsystem.Auction.Bid:input_type -> auctionsystem.amount
	10, // 10: auctionsystem.Auction.Result:input_type -> google.protobuf.Empty
	7,  // 11: auctionsystem.ReplicationSync.Fetch:input_type -> auctionsystem.self
	7,  // 12: auctionsystem.ReplicationSync.Heartbeat:input_type -> auctionsystem.self
	7,  // 13: auctionsystem.ReplicationSync.RegisterNode:input_type -> auctionsystem.self
	7,  // 14: auctionsystem.ReplicationSync.GetCluster:input_type -> auctionsystem.self
	6,  // 15: auctionsystem.Auction.Bid:output_type -> auctionsystem.ackmsg
	4,  // 16: auctionsystem.Auction.Result:output_type -> auctionsystem.resultmsg
	8,  // 17: auctionsystem.ReplicationSync.Fetch:output_type -> auctionsystem.AuctionData
	10, // 18: auctionsystem.ReplicationSync.Heartbeat:output_type -> google.protobuf.Empty
	10, // 19: auctionsystem.ReplicationSync.RegisterNode:output_type -> google.protobuf.Empty
	5,  // 20: auctionsystem.ReplicationSync.GetCluster:output_type -> auctionsystem.ClusterInfo
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_grpc_auctionsystem_proto_init() }
func file_grpc_auctionsystem_proto_init() {
	if File_grpc_auctionsystem_proto != nil {
		return
	}
	file_grpc_auctionsystem_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auctionsystem_proto_rawDesc), len(file_grpc_auctionsystem_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_auctionsystem_proto_goTypes,
		DependencyIndexes: file_grpc_auctionsystem_proto_depIdxs,
		EnumInfos:         file_grpc_auctionsystem_proto_enumTypes,
		MessageInfos:      file_grpc_auctionsystem_proto_msgTypes,
	}.Build()
	File_grpc_auctionsystem_proto = out.File
	file_grpc_auctionsystem_proto_goTypes = nil
	file_grpc_auctionsystem_proto_depIdxs = nil
}
